### ISSUE TITLE
Enable AudioUnit Echo Cancellation for iOS SDK

### ISSUE THREAD

**Issue by petrugaspar** [aws/amazon-chime-sdk-ios#404] opened 2022-02-18 09:17 UTC
We are using [amazon-chime-sdk-ios](https://github.com/aws/amazon-chime-sdk-ios) to develop a VOIP conference app that allows a participant to present audio-video content to other participants. If one of the participants watches the content playing while on speaker then the microphone of the device captures the sound coming from the speaker and redirects it back into the call causing an echo issue for the other participants. 

I have enabled Amazon Voice Focus for the project but it doesn't help with the issue.  

From my research I understand that iOS has a built in system called AudioUnit Echo Cancellation (AEC) that would help fix the issue, do you plan or can you add support for Audio Units to access the system's echo cancellation into the Chime SDK for iOS?

Reproducible on iPhone 12 PRO with iOS 15.1 , Amazon chime sdk version 0.18.0 with CallKit integration.

**Comment by achronop** [comment] 2022-02-22 12:35
Thank you for the suggestion. The truth is we already do audio processing on the input audio and one of the steps is the Echo Canceling. We have different solutions for audio processing according to the platform that you are on and the audio configuration (sample rate, channel count) but all of them include EC. One of the solution involve the AudioUnit audio processing.

Would you like to elaborate on the scenario that you see the echo. The expectation is that the echo will be canceled but there are limitation on that if the output of the remote party is very loud for example. Can you comment also on the audio configuration that you use?

**Comment by petrugaspar** [comment] 2022-02-22 14:52
The scenario is that during a video conference if one of the participants plays a video presentation to the other participants and one of them is watching the content using the built-in phone speaker and not using headphones, than the audio output of the speaker will be captured by the phone microphone and redirected back into the conference creating the echo effect for the other participants (they hear the video content twice). The best approach would be to cancel all the sounds being played from the phone speakers, from my understanding AudioUnit can perform Built-in Features such as echo cancellation to cancel the audio being played from the speakers. I don't use any custom audio configuration, I am using the Amazon chime audio configuration and AVAudioSession to set the category and mode.

**Comment by achronop** [comment] 2022-02-22 15:30
IIUC participant with the speaker on is an iPhone 12 PRO with iOS 15.1. What happens if you change the volume of that device to something lower. Is the volume at top most? Is there a lower volume level (above zero of-course) that eliminates the bad effect?

**Comment by petrugaspar** [comment] 2022-02-22 15:55
It's reproducible for iPhone 12 PRO with iOS 15.1 and iPhone SE with iOS 13.3, I don't think it's related to the phone model or iOS version. If the participant playing the video on speaker reduces the volume on that device to 10% percent than the echo is not distinguished anymore, otherwise it's hearable on all other volumes 20% to 100%. The issue with this is that the participant cannot hear the video presentation properly on 10% volume.

**Comment by achronop** [comment] 2022-02-22 16:14
10% is very low, I would expect that EC would operate with louder volumes. I will try to repro locally. One more question though, does the video contain music or just voice? Do you have a representative sample?

**Comment by petrugaspar** [comment] 2022-02-22 16:22
It can contain both music and voice, I don't have a specific sample you can use the video player to play a music video from Youtube for example, it covers all the diferent scenarios (music and voice).

**Comment by achronop** [comment] 2022-02-23 10:49
One more thing, if you try the same scenario but you talk instead of playing a video, does it create the same echo effect from the party that listens from the speaker?

**Comment by petrugaspar** [comment] 2022-02-23 11:48
Tested and it doesn't create an echo effect if the participants only talk during the session. I presume the voice of the speaker is canceled by CallKit or by default by the system and it's not captured by the microphone even when on speaker.

**Comment by achronop** [comment] 2022-02-23 14:26
Thanks, probably we fail to feed back the reference signal when we play content. In normal talking we must do the right thing. Let me investigate that direction. BTW is there a difference if the CallKit is off?

**Comment by achronop** [comment] 2022-03-01 16:27
I am testing the scenario and I cannot reproduce the problem. My setup is an iPhone that is running the iOS demo. From another end point, a desktop I am running the JS demo. I play a video with music and voices from the JS demo. I keep JS demo muted. The iOS demo's output is in the loud speaker. To check the echo I try to observer any sound arriving in the JS demo. The result is that an echo is not observed. Also, I double check the audio path and I verified that there is [only one audio client instance](https://github.com/aws/amazon-chime-sdk-ios/blob/71dd4a92cabe73b2e98ffa0556d0320c0763eef9/AmazonChimeSDK/AmazonChimeSDK/internal/audio/DefaultAudioClient.swift#L16). Audio client is responsible for audio record and playback. Since there is only one instance, the audio processing in it, is executing and it is expected to cancel the echo.

Would you like to share more about your setup and the way that you use the API. Has your implementation diverged from the existing demo?

**Comment by petrugaspar** [comment] 2022-03-01 16:55
Yes, the implementation has diverged from the demo, so it may seem there is an issue with the audio client instance, i looked into the code and we have no access to the audio client, it's initialised when creating a DefaultMeetingSession. CallKit requires that an AudioSession is configured before starting an incoming / outgoing call so it can activate the audio session, can this interfere with the audio client? 

Can you test with a CallKit integration? 

My setup is creating a session between 2 iPhones (iOS 15.1 and iOS 13.3) with CallKit integration.

**Comment by petrugaspar** [comment] 2022-03-02 12:42
Also I am using an AVPlayerViewController to play the multimedia (video / audio) content while in the session , can this also interfere with the audio client?

**Comment by petrugaspar** [comment] 2022-03-03 14:10
We can discuss it further in a private channel, how can I create / join a private channel?

**Comment by achronop** [comment] 2022-03-03 15:44
I'm afraid you have to go through the customer support. You have to open a support ticket via your AWS console.

**Comment by georgezy-amzn** [comment] 2022-05-26 00:52
Closing since it has been resolved via a private channel. Feel free to reopen it if you still have any issues.

**Closed by georgezy-amzn** 2022-05-26 00:52 UTC
Labels: feature-request

**Comment by yoihito** [comment] 2023-05-30 19:58
Did you solve this issue? Can you please share what is the solution?

**Comment by ashirkhan94** [comment] 2023-09-18 06:15
Hi @georgezy-amzn 
What is the solution to this issue?
