### ISSUE TITLE
AmazonChimeSDK crash __exceptionPreprocess -[__NSArray0 objectAtIndex:] + 112 (CFArray.c:103)

### ISSUE THREAD

**Issue by manghwanitin** [aws/amazon-chime-sdk-ios#284] opened 2021-04-20 05:34 UTC
We are getting this crash in chime SDK. This crash has occurred 4 times in last 30 days and 8 time in last 90 days.
When we try to symbolicate we found below logs in last exception trace.

DefaultAudioVideoController.addAudioVideoObserver(observer:) (in AmazonChimeSDK) (DefaultAudioVideoController.swift:68)
DefaultAudioVideoFacade.logger.getter (in AmazonChimeSDK) (DefaultAudioVideoFacade.swift:13)
closure #1 in DefaultActiveSpeakerDetector.attendeesDidJoin(attendeeInfo:) (in AmazonChimeSDK) (DefaultActiveSpeakerDetector.swift:157)

Attaching .crash file for reference
[IndexOutOfBounds.crash.zip](https://github.com/aws/amazon-chime-sdk-ios/files/6340840/IndexOutOfBounds.crash.zip)

**Comment by ziyiz-amzn** [comment] 2021-04-21 21:42
Hi @manghwanitin 

Would you mind providing these details? 
* Version of AmazonChimeSDK: [e.g. 0.4.0]
* Version of AmazonChimeSDKMedia: [e.g. 0.4.0]
* It this crash is consistently occuring, can you provide reproduce steps?
* Are you using binaries with or without bitcode?

**Comment by manghwanitin** [comment] 2021-04-22 05:45
@ziyiz-amzn 
Hello 
Please find the details as below
1. We are using version 0.8.1 of AmazonChimeSDK
2. Version of AmazonChimeSDKMedia os 0.6
3. Crash has occurred 8 times in past 90 days
4. We are using binaries without bitcode.

**Comment by ziyiz-amzn** [comment] 2021-04-22 20:08
@manghwanitin  Thank you for the info.

While we are investigating this issue, could you 
1.  provide the specific steps to reproduce the crash? 
2. try to use a more latest version of SDK and media SDK?
https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.16.2

**Comment by manghwanitin** [comment] 2021-04-23 04:54
@ziyiz-amzn 
Hello
1. We did tried to update the chime SDK in our process. However we are facing certain issue while testing so that is still under investigation.
2. This crash happened on production in our our mobile. So we do not have specific steps to reproduce the crash.

I would like to know were you able to symbolicate the crash logs and found anything from that?

**Comment by ziyiz-amzn** [comment] 2021-04-23 23:17
Hi @manghwanitin 

We symbolicated the crash log and locate where the issue happened. 

```
4   AmazonChimeSDK                	0x10aafe054 specialized _ArrayBuffer._getElementSlowPath(_:) + 15532 (<compiler-generated>:0)
5   AmazonChimeSDK                	0x10aafd25c closure #1 in DefaultDeviceController.handleSystemAudioChange(notification:) + 152156 (<compiler-generated>:0)
6   AmazonChimeSDK                	0x10ab0f5ec thunk for @escaping @callee_guaranteed () -> () + 226796 (<compiler-generated>:0)
```

It is the same root cause as https://github.com/aws/amazon-chime-sdk-ios/issues/148, which has been fixed in https://github.com/aws/amazon-chime-sdk-ios/pull/151 and released. 

It should be working well after 0.13.0. But we highly recommend that you can apply most recent versions of both mobile and media SDK.

Please let us know if any more question.

**Comment by manghwanitin** [comment] 2021-04-24 12:37
@ziyiz-amzn  Thank you so much for update. As I mentioned earlier we are looking forward to update to latest SDK and that task is in progress

**Closed** 2021-04-26 16:42 UTC
Labels: Needs More Information
