### ISSUE TITLE
Captured video from camera is not complete

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-ios#238] opened 2021-02-17 14:58 UTC
**Describe the bug**

Before using `amazon-chime-sdk-ios` to send my video to a Chime meeting, I display a preview of my camera.
To do so I use `react-native-camera` (it is a React Native project).
While displaying the preview I get the following image :

<img width="332" alt="Capture d’écran 2021-02-17 à 15 51 16" src="https://user-images.githubusercontent.com/2794137/108221340-f99eb580-7137-11eb-9435-c8e1a7e20b7b.png">

Then when I join to the Chime meeting and send my video, I get the following image :

<img width="320" alt="Capture d’écran 2021-02-17 à 15 51 58" src="https://user-images.githubusercontent.com/2794137/108221438-120ed000-7138-11eb-9a74-c1f28a3e0d06.png">

As you can see, I have lost the left stripe and 2 rectangles on the right side.
At first, I thought it was my fault by displaying the video view in the wrong way.

But since my solution already works in the browser (thanks to the amazing `amazon-chime-sdk-js`), I was able to display this same video (sent from my iPhone) into my browser (Google Chrome on macOS) and display this video in Picture-to-Picture.
Here is what I get :

![image](https://user-images.githubusercontent.com/2794137/108221885-8ba6be00-7138-11eb-8a9b-d181ffbcdff9.png)
 
The left stripe and 2 rectangles are also missing here.

This means that the camera capture is not complete, causing some kind of "zoom effect".
Were you able to notice this problem ? Would it be easy to fix ?
Thanks in advance !

**Test environment Info (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.4
 - Version AmazonChimeSDK: 0.15.0
 - Version AmazonChimeSDKMedia: 0.11.0

**Comment by zhinang-amazon** [comment] 2021-02-17 17:49
Hi @rlebosse,
I think the problem is that the camera configuration during your preview is different from the configuration during video sharing.
Here is our [`DefaultCameraCaptureSource`](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/capture/DefaultCameraCaptureSource.swift#L13)
Possible solutions:
1. Configure the camera preview using `react-native-camera` to be the same as our `DefaultCameraCaptureSource`. Default capture value: `AVCaptureDevice.DeviceType.builtInWideAngleCamera`, 720 x 1280
2. Use our `DefaultCameraCaptureSource` for preview. This ensures that the format will be the same as the one during video sharing, but will require more coding. Our native iOS and Android demo app currently have this functionality. Take a look at this [guide](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/custom_video.md)

**Comment by zhinang-amazon** [comment] 2021-03-24 17:18
Closing this issue. If you still have question around this, feel free to reopen.

**Closed by zhinang-amazon** 2021-03-24 17:18 UTC
Labels: question
