### ISSUE TITLE
Can't lower volume all the way

### ISSUE THREAD

**Issue by nealmanaktola** [aws/amazon-chime-sdk-ios#215] opened 2021-01-20 19:52 UTC
**Describe the bug**
Sound doesn't completely go away when lowering the volume. If I try to lower the volume all the way, audio still comes through when connected to a meeting this doesn't seem right?

**To Reproduce**
1. Start meeting
2. Try lowering the volume all the way
3. You can still hear the attendees

This is 100% reproducible on iOS and Android

**Expected behavior**
No audio should be heard when volume is completely lowered

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.3
 - Version AmazonChimeSDK: [e.g. 0.12.2]
 - Version AmazonChimeSDKMedia: [e.g. 0.8.2]

**Additional context**

**Comment by hokyungh** [comment] 2021-01-21 00:06
Thanks for opening the issue. I think we need more investigation on our end.

**Comment by nealmanaktola** [comment] 2021-02-25 23:36
Any update on this one?

**Comment by hokyungh** [comment] 2021-02-26 03:10
Sorry for late response. I was able to reproduce it. Just trying to find out if this is correct behavior or not. Will update this thread once I have answer for it.

**Comment by nealmanaktola** [comment] 2021-02-26 17:45
Thanks @hokyungh as a reminder this is reproducible on Android too. Let me know if you need me to create an issue on there as well.

**Comment by hokyungh** [comment] 2021-02-26 19:32
@nealmanaktola It doesn't look like a bug, but a feature in the call where you can't lower volume to certain threshold. Otherwise, you will not be know if you are in the call due to volume. In the actual call, you will not be able to lower volume either. We'll close this issue. Let me know if you have further question.

**Closed by hokyungh** 2021-02-26 19:32 UTC
Labels: needs investigation

**Comment by nealmanaktola** [comment] 2021-02-26 22:48
The volume is still really loud..esp on Android. Is there something you can do there?

**Comment by hokyungh** [comment] 2021-02-26 23:03
@nealmanaktola if you are using speaker, could you switch to built-in earpiece? We can later add feature to mute output and update this https://github.com/aws/amazon-chime-sdk-ios/issues/250 thread.
