### ISSUE TITLE
App crashes when turning on camera

### ISSUE THREAD

**Issue by tuneerclixlogix** [aws/amazon-chime-sdk-ios#205] opened 2021-01-08 12:19 UTC
App gets crashed when set camera on with NativeFunction.setCameraOn(true) in react native for ios.

**Logs**
[DEFAULT] NativeMobileSDKBridge - [015:394] [66571] (video_stream_encoder.cc:1038): Video frame parameters changed: dimensions=1280x720, texture=1.
2021-01-08 17:42:39.740308+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:395] [66571] (video_stream_encoder.cc:572): ReconfigureEncoder:
Simulcast streams:
0: 640x360 fps: 15 min_bps: 150 target_bps: 187 max_bps: 250 max_fps: 15 max_qp: 56 num_tl: 3 active: true
1: 1280x720 fps: 15 min_bps: 350 target_bps: 600 max_bps: 800 max_fps: 15 max_qp: 56 num_tl: 3 active: true
2021-01-08 17:42:39.740502+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:396] [66571] (RTCVideoEncoderH264.mm:354): Using profile H264_Baseline_3_1
2021-01-08 17:42:39.740550+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:396] [66571] (RTCVideoEncoderH264.mm:363): Encoder using gpu_acceleration: 1
2021-01-08 17:42:39.740605+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:396] [66571] (simulcast_encoder_adapter.cc:317): VideoEncoder[0] Init 640x360 fr:15 mbr:250
2021-01-08 17:42:39.743697+0530 Eldertech[19375:1329686] [INFO] NativeMobileSDKBridge - Binding VideoView to Tile with tileId = 0
2021-01-08 17:42:39.743741+0530 Eldertech[19375:1329686] [INFO] NativeMobileSDKBridge - Binding the view to tile: tileId: 0, attendeeId: 51420e24-052d-c111-ed31-e712ea6ec0f5
2021-01-08 17:42:39.754173+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:409] [66571] (RTCVideoEncoderH264.mm:354): Using profile H264_Baseline_3_1
2021-01-08 17:42:39.754260+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:409] [66571] (RTCVideoEncoderH264.mm:363): Encoder using gpu_acceleration: 1
2021-01-08 17:42:39.754319+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:410] [66571] (simulcast_encoder_adapter.cc:317): VideoEncoder[1] Init 1280x720 fr:15 mbr:800
2021-01-08 17:42:39.760787+0530 Eldertech[19375:1333063] [DEFAULT] NativeMobileSDKBridge - [015:416] [66571] (video_stream_encoder.cc:671):  max bitrate 1050 start bitrate 700 max frame rate 15 max payload size 1080
(lldb) 

**Screenshots**
![image](https://user-images.githubusercontent.com/72122766/104014450-0e069e80-51d9-11eb-828e-0e0dc2154ce4.png)

**Test environment Info (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS14.1

**Comment by zhinang-amazon** [comment] 2021-01-12 22:23
Hi @tuneerclixlogix,

I'm not able to reproduce this issue with our RN demo app. 
Can you provide more information on what AmazonChimeSDK, AmazonChimeSDKMedia version you are using?

Please also try to reproduce with iOS or RN demo app and provide repro steps to help us investigate the issue.

**Comment by tuneerclixlogix** [comment] 2021-01-13 10:15
Hello @zhinang-amazon 
I have used the AmazonChimseSDK version 0.13.1 and AmazonChimeSDKMedia version 0.9.0
Xcode version 12.3
Ios version 14.3

When i set the NativeFunction.setCameraOn(true) it switch on the camera and bind the video and the application hangs there.

I will give a try with the demo and share the details

**Comment by zhinang-amazon** [comment] 2021-01-13 22:25
Hi @tuneerclixlogix 
I see that you opened an issue in the RN demo repo also: https://github.com/aws-samples/amazon-chime-react-native-demo/issues/45

I will close this one and track the issue there since it's related to RN usage.

**Closed by zhinang-amazon** 2021-01-13 22:25 UTC
