### ISSUE TITLE
Starting DefaultCameraCaptureSource from background thread causes UI to freeze

### ISSUE THREAD

**Issue by keverly** [aws/amazon-chime-sdk-ios#379] opened 2021-12-06 22:54 UTC
When using `DefaultCameraCaptureSource`, calling the `start()` function from a thread other than `main` causes the main thread to hang for about 10 seconds. This results in the UI to becoming unresponsive. This issue only seems to affect devices running **iOS 14 and below.**

### Steps to Repro
1. Setup Demo App on a device running iOS 14 (or below)
2. Wrap [customSource.start()](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/VideoModel.swift#L50) with `DispatchQueue.global().async`
3. In the demo app. Turn video on, off, and on again (sometimes it takes a few tries. It's consistent for the most part though. I'd say 95% repro rate). 

https://user-images.githubusercontent.com/52120465/144930396-be8aa217-379e-411e-ba43-dd4826d94736.mp4

You can see the video on/off button toggle when I press it. There is a significant delay before the video actually turns on. The whole UI is frozen during this time.

### Versions
Chime SDK: 0.17.0
ChimeSDKMedia: 0.13.0

### Notes
I've been calling `start()` from non-main thread since it calls `session.startRunning` which takes some time and is a blocking operation according to [Apple](https://developer.apple.com/documentation/avfoundation/avcapturesession/1388185-startrunning). I don't think requiring callers to be on the main thread is the right approach.

 I messed around with some things and came to the conclusion that setting the[ connection.videoOrientation](https://github.com/aws/amazon-chime-sdk-ios/blob/ecae6f318206e150530da538b2b7ae2db02f4a83/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/capture/DefaultCameraCaptureSource.swift#L204) on the main thread is the culprit. As to "why" it causes an issue, I still cannot say. However Wrapping this switch in a non-main thread seems to fix the problem...

```swift
DispatchQueue.main.async {
    // statusBarOrientation  needs to be accessed from main, which is why the main thread was originally used.
    self.orientation = UIApplication.shared.statusBarOrientation 
  
    self.testQueue.async {
        switch self.orientation {
        case .portrait, .unknown:
            connection.videoOrientation = .portrait
        case .portraitUpsideDown:
            connection.videoOrientation = .portraitUpsideDown
        case .landscapeLeft:
            connection.videoOrientation = .landscapeLeft
        case .landscapeRight:
            connection.videoOrientation = .landscapeRight
        @unknown default:
            break
        }
    }
 }
``` 
This still has an issue where after starting the video and immediately turning the device, the orientation isn't updated for until the ~10 sec time frame is up. 

### Summary
When calling `DefaultCameraCaptureSource.start()` from a non-main thread, setting `connection.videoOrientation` becomes a blocking operation for about 10 seconds on iOS 14 and below. A mitigation is to set the videoOrientation on a thread besides main, but that is just moving the bug to a less important thread so it's not as noticeable to users. I don't know what the true cause is unfortunately.

**Comment by hokyungh** [comment] 2021-12-10 09:24
Thanks for detailed investigation, I was able to reproduce this in one of iOS 14 devices, but not in iOS 12 device. Will continue to investigate based on your finding.

**Comment by keverly** [comment] 2021-12-14 20:30
Thanks @hokyungh. I only tested on iOS 14 and one of my teammates saw the issue on iOS 13. Based on this I inferred it was iOS 14 and below, but may just affect those two.

**Comment by zhorben** [comment] 2021-12-15 02:26
We are facing the same issue. The application hangs for a time between 4-10 seconds. Our application is based on react-native (expo). We use code samples from [demo repo](https://github.com/aws-samples/amazon-chime-react-native-demo/).
Calling **setCameraOn** from [Bridge.js](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/utils/Bridge.js) causes the whole application to hang. The issue only occurs when we switch the camera to "on" - **setCameraOn(true)**. But the issue doesn't occur on all devices.

### **Devices on which we can reproduce the freeze:**
iPad Pro (11in), iOS 14.8.1
iPad Pro (11in), iOS 14.7.1

### **Devices on which we can't reproduce the freeze:** 
iPad (7th generation), iOS 14.7.1
iPad Air (4th generation), iOS 15.1

### **Versions of**
Chime SDK: 0.17.0 and 0.16.4 
ChimeSDKMedia: 0.13.0 and 0.12.0
Expo: 42 and 43

### **What we found and what we tried:**
1. Upgrading Expo because of updated dependencies (ReactNative, expo-camera with possible fixes for freezing/performance issues)
2. Upgrading to latest Chime SDK due to some performance improvements/fixes there too
3. Tweaking different build parameters in XCode (i.e. building with bitcode and no bitcode)
4. In the end we found out that 3 out of 3 iPad Pros have the issue while 3 out of 3 non-Pros don't have the issue

**Comment by nikitatsvirkosoft** [comment] 2021-12-20 15:43
Calling `[meetingSession.audioVideo startLocalVideoAndReturnError:&error];` from non-main thread cause the freezing in our case with @zhorben. I fixed the freeze by calling this method on main thread:
```obj-c
dispatch_async(dispatch_get_main_queue(), ^{
   NSError* error;
   [meetingSession.audioVideo startLocalVideoAndReturnError:&error];
   if(error != nil)
   {
     [self sendEventWithName:kEventOnError body:@"Fail to start local video"];
   }
});
```

**Comment by ziyiz-amzn** [comment] 2022-05-07 04:19
Closing it now, feel free to reopen it if still see issue.

**Closed by ziyiz-amzn** 2022-05-07 04:19 UTC
Labels: bug
