### ISSUE TITLE
Archiving bitcode errors

### ISSUE THREAD

**Issue by imamark** [aws/amazon-chime-sdk-ios#11] opened 2020-04-14 14:32 UTC
I'm able to build and launch my app in the simulator and my connected device but when archiving my app using Xcode 11.4, I get Bitcode errors. 

**Logs**
ld: bitcode bundle could not be generated because '/Users/xxxx/MYAPP/AmazonChimeSDK.framework/AmazonChimeSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/xxxx/MYAPP/AmazonChimeSDK.framework/AmazonChimeSDK' for architecture arm64

**Test environment Info:**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS13]
 - Version AmazonChimeSDK: [e.g. 0.5.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.5.0]

**Additional context**
I'm also not able to archive the actual SDK in this repository with the same errors, but referring to the AmazonChimeSDKMedia framework instead.

I think maybe the fix is:

a) Rebuild both the AmazonChimeSDK & AmazonChimeSDKMedia 0.5.0 distributions with bitcode enabled
b) or include the AmazonChimeSDKMedia repo so we can build the frameworks locally ourselves with bitcode enabled

**Comment by tianyux-amz** [comment] 2020-04-15 19:55
Hi @imamark ,

We are able to reproduce the issue. We will release a new AmazonChimeSDKMedia framework with full bitcode support in the next SDK release, which is expected to happen next week.

**Comment by imamark** [comment] 2020-04-16 06:53
That's great thanks @tianyux-amz 👍

**Comment by tianyux-amz** [comment] 2020-04-23 20:57
Hi @imamark,

We released iOS SDK v0.5.1 today, which contains frameworks with and without bitcode data. Please check the latest "[Download the binaries](https://github.com/aws/amazon-chime-sdk-ios#1-download-binaries)" section and see if it resolves your issue. Thanks!

**Comment by mitankit** [comment] 2020-04-27 21:56
Could you please confirm if the issue is resolved with 0.5.1 version?

**Comment by mitankit** [comment] 2020-05-12 19:51
We are closing this issue due to lack of response from the reporter. Please feel free to reopen or create a new issue if you still see the issue.

**Closed by mitankit** 2020-05-12 19:51 UTC
