### ISSUE TITLE
Phone rotation video issue.

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws/amazon-chime-sdk-ios#182] opened 2020-12-11 17:19 UTC
**Describe the bug**
The preview video is upside down in landscape.

**To Reproduce**
1. Launch the demo app `AmazonChimeSDKDemo`.
2. Enter a Meeting ID and Your name (the values do not matter). 
3. Tap "Join Without CallKit"
4. You see your self in the "Video Preview"
5. Rotate your phone in landscape : you are upside down.

**Expected behavior**
It should not be upside down.

**Test environment Info (please complete the following information):**
 - iPhone 11 Pro Max
 - OS: iOS 12.2
 - Version AmazonChimeSDK: 0.12.1
 - Version AmazonChimeSDKMedia: 0.8.1

**Comment by hokyungh** [comment] 2020-12-17 19:26
Thanks for reporting. This might be related to https://github.com/aws/amazon-chime-sdk-ios/issues/88. We'll label it as bug.

**Comment by tianyux-amz** [comment] 2021-01-05 01:50
Hi @LilianAlvarez123,

I tried to reproduce the issue by following your steps, but I was not able to reproduce it.

Here is what I did:
1. Launched the demo app AmazonChimeSDKDemo v0.12.1 in *portrait mode*, and tap "Join Without CallKit".
2. See local video in "Video Preview", with correct video orientation.
3. Rotate the phone to landscape. The demo app layout changed to landscape, and local video preview was also rotated as expected.

Here is a screen recording for my testing:
![RPReplay_Final1609808450 2021-01-04 17_47_12](https://user-images.githubusercontent.com/40373084/103597350-ee0f6c00-4eb4-11eb-8fbd-31401e564d8d.gif)

I did notice that when you start rotating the device, the video seemed to be upside down before the UI layout also changed to landscape mode. This is caused by a different bug in our demo app that we did not mirror the front camera properly. I will prepare a fix for this issue.

Best,
Tianyu

**Comment by LilianAlvarez123** [comment] 2021-01-05 08:27
Hello @tianyux-amz 

I am so sorry, I forget to say, you need to have only the "portrait" mode activated. One this done, you will see that the video rotate even if it's not configured has he should.

Lilian.

**Comment by tianyux-amz** [comment] 2021-01-05 20:21
@LilianAlvarez123 Thanks for the clarification. In that case, PR #198 will fix the issue, and the issue is not related to #88. I'll let you know once the fix is merged in.

**Comment by tianyux-amz** [comment] 2021-01-06 01:36
The fix was merged and pending release.

**Comment by hokyungh** [comment] 2021-01-22 05:32
The fix has been published. Feel free to reopen if you still have issue.

Thanks!

**Closed by hokyungh** 2021-01-22 05:32 UTC
Labels: bug
