### ISSUE TITLE
Video Tile modifications from Web not triggering on iOS

### ISSUE THREAD

**Issue by an-kumar** [aws/amazon-chime-sdk-ios#113] opened 2020-09-11 04:24 UTC
Various video tile notifications are not being triggered in the RealtimeObserver when the remote attendee is on web.

**To Reproduce**

1. Open web client and mobile client, and join the same meeting.
2. Toggle video on and off on the web client
3. The iOS client will receive `videoTileDidRemoveWithTileState` when the web client toggles their video off, but *not* `videoTileDidAddWithTileState` when the web client toggles their video back on. `videoTileDidPauseWithTileState` and `videoTileDidResumeWithTileState` are not called either.

**Expected behavior**
I expected the iOS client to receive either `videoTileDidAddWithTileState` or `videoTileDidResumeWithTileState`.

**Logs**
One log worth looking at is:

2020-09-10 20:36:48.442882-0700 rn[43046:4877775] [ERROR] NativeMobileSDKBridge - [789:559] [66563] (webrtc_video_engine.cc:3264): Absent receive stream; ignoring clearing encoded frame sink for ssrc 0

followed, after a little bit of inactivity, by:

[800:149] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[801:154] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[802:158] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[803:162] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[804:168] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[805:172] [67591] (video_renderer_adapter.cc:196): 10 metrics frames sent with 0 FPS;
...

This is logged *every time the web client toggles their video back on*; so it seems likely that the event is indeed getting to the iOS client, but some error is causing it to not trigger up to the SDK.

**Test environment Info (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.6
 - Version AmazonChimeSDK: 0.10.0
 - Version AmazonChimeSDKMedia: 0.6.2

**Comment by tianyux-amz** [comment] 2020-09-18 10:14
Hi @an-kumar ,

Thank you for reaching out.

I saw `NativeMobileSDKBridge` in the attached log. Are you running [the React Native demo app](https://github.com/aws-samples/amazon-chime-react-native-demo) provided by us?

FYI, [videoTileDidPauseWithTileState](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/cabe07a5001d1dbc5c5fc08b960d957a9880f256/ios/RNDemo/MeetingObservers.m#L89-L92) and [videoTileDidResumeWithTileState](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/cabe07a5001d1dbc5c5fc08b960d957a9880f256/ios/RNDemo/MeetingObservers.m#L99-L102) were not implemented in the demo app, so it's expected that you won't get any callback unless you implement them by yourself. However, I do see `videoTileDidAddWithTileState` being triggered properly in the demo app.

Best,
Tianyu

**Comment by an-kumar** [comment] 2020-09-18 20:07
I am using the ReactNative demo app.

I modified the native code to implement the `didPause` and `didResume` callbacks.

The issue is not that `videoTileDidAddWithTileState` is never triggered; the issue is that when the remote client is toggling their video off and on, it is not _re_-triggered.

**Comment by tianyux-amz** [comment] 2020-09-18 21:09
Hi @an-kumar ,

Thanks for the clarification. I actually meant I was able to see `videoTileDidAddWithTileState` triggered *multiple times* as I toggle the remote videos.

Could you please try to checkout a fresh (unmodified) RN demo and follow the [instructions here](https://github.com/aws-samples/amazon-chime-react-native-demo#how-to-run-the-react-native-demo-application) to see if you can re-trigger `videoTileDidAddWithTileState` properly? If you still see issues in the unmodified RN demo, could you also try it on different devices and see if the issue persists?

Tianyu

**Comment by mj8894** [comment] 2020-09-26 10:08
Hi Team,

There seems to be a similar issue in native iOS App as well. Also I am noticing that in case a video is paused on Web, a screenshot from nearest tile next to it is binded to the videorenderview

**Comment by zhinang-amazon** [comment] 2020-09-28 17:21
Hi @mj8894 ,
I'm able to receive `videoTileDidAddWithTileState ` with our iOS demo app when video is turned back on from web demo.
Are you able to reproduce with our iOS demo app?

Regarding your issue with "a screenshot from nearest tile next to it is binded to the videorenderview", are you properly cleaning up `videorenderview` for reuse? If you are using a `UICollectionViewCell`, this should be in `prepareForReuse()` method similar to [VideoTileCell](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/VideoTileCell.swift#L63) in our demo app.

**Comment by mj8894** [comment] 2020-09-29 04:48
Hi @zhinang-amazon ,

I am using the `prepareforReuse()` exactly as it is in the demo app, Also, I have noticed that `videoTileDidAddWithTileState` is not called everytime a video tile is added, Out of 10 times I toggled video on web, 6 times the video add notification was not fired.

**Comment by MaxQuantumCake** [comment] 2020-11-05 09:46
Hello, 
Any news about this bug ?

**Comment by rlebosse** [comment] 2020-11-05 09:53
I am facing the exact same issue :

* Initial conditions : empty Chime Meeting (freshly created, no attendees)
* Mobile user : joins the Meeting (audio off / video off)
* Web user :  joins the Meeting (audio off / video on)
* Mobile side : reception of the event `videoTileDidAddWithTileState` with `tileId = X` ✅
* Web user : turns camera off in the Meeting
* Mobile side : reception of the event `videoTileDidRemoveWithTileState` with `tileId = X` ✅
* Web user : turns camera back on in the Meeting
* Mobile side : **NO** reception of the event `videoTileDidAddWithTileState`  :x: 
* Web user : turns camera off in the Meeting
* Mobile side :  reception of the event `videoTileDidRemoveWithTileState` avec `tileId = X` ✅

**Comment by LilianAlvarez123** [comment] 2020-11-05 09:56
Hello Amazon Chime,

I am facing the same exact issue as described by @rlebosse.

Have you any workaround solution ?

**Comment by hokyungh** [comment] 2020-11-05 17:18
@rlebosse , @LilianAlvarez123 Do you know in the videoTieleDidRemove, you call `audioVideo.unbindVideoView(tileId)`?

**Comment by LilianAlvarez123** [comment] 2020-11-06 09:09
Hello @hokyungh, yes, we have tried the fix in the PR : https://github.com/aws/amazon-chime-sdk-ios/pull/160.

It does solve the problem. Could you guys make another release with this PR ? It would resolve this issue here.

@hokyungh @linsang21 

Thank you guys !

**Comment by zhinang-amazon** [comment] 2020-11-06 17:44
Hi @LilianAlvarez123 
#160 will be in the next release ~2 weeks.
But that change is in our ObjC demo app, not the SDK target though.
If your app uses similar UI logic as our ObjC demo app, you can make the same change without new SDK release, correct?

**Comment by LilianAlvarez123** [comment] 2020-11-09 08:08
Hello,

How about the #154 PR, that fixes the issue with the remote vidéo ?

It put a lot of constraint on our team to wait 2 weeks. Would it be possible to speed up the process on your side please ?

It would be a great help. @zhinang-amazon
 
https://github.com/aws/amazon-chime-sdk-ios/pull/154

**Comment by LilianAlvarez123** [comment] 2020-11-13 16:18
Hello guys !

Any news @zhinang-amazon about the new release ? :pray: 

Thank you very much.

**Comment by tianyux-amz** [comment] 2020-11-26 00:21
Hi @LilianAlvarez123 ,

#154 was released in v0.12.0 on 2020-11-17. The latest SDK version is v0.12.1. Feel free to try it out, and let us know if you have more questions. Thanks!

**Closed by tianyux-amz** 2020-11-26 00:21 UTC
Labels: bug
