### ISSUE TITLE
No support for SPM in 2023

### ISSUE THREAD

**Issue by oliverfoggin** [aws/amazon-chime-sdk-ios#598] opened 2023-05-16 18:19 UTC
**Describe the bug**
This framework doesn't support Swift Package Manager.

**To Reproduce**
1. Go to https://github.com/aws/amazon-chime-sdk-ios
2. See error

**Expected behavior**
Any iOS framework from a large company in 2023 should support Swift packaged Manager.

**Logs**
N/A

**Screenshots**
N/A

**Test environment Info (please complete the following information):**
N/A

**Additional context**
N/A

Please add support for SPM.

**Comment by hokyungh** [comment] 2023-05-16 18:24
Duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/338. We are currently working on it and will soon release swift package manager.

**Closed by hokyungh** 2023-05-16 18:24 UTC

**Comment by oliverfoggin** [comment] 2023-05-16 18:25
@hokyungh great! Thanks! Perhaps a comment with an ETA in the linked issue would help put people at ease? Thanks
