### ISSUE TITLE
Specify max bandwidth for input video source

### ISSUE THREAD

**Issue by Jim-Bar** [aws/amazon-chime-sdk-ios#476] opened 2022-05-20 10:09 UTC
It is possible to set a custom video input format with a custom [CameraCaptureSource](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.audiovideo.video.capture/-camera-capture-source/index.html). However it is not possible to set a max bandwidth as it is possible to do in `amazon-chime-sdk-js` with `chooseVideoInputQuality(width, height, frameRate, maxBandwidthKbps)`.

I would need finer control on the bandwidth used to send the video, is this a planned feature?

Related on the `amazon-chime-sdk-android` project: [I need chooseVideoInputQuality(maxBandwidthKbps)](https://github.com/aws/amazon-chime-sdk-android/issues/438).

Thank you.

**Comment by ziyiz-amzn** [comment] 2022-05-25 00:07
@Jim-Bar Thank you for the interest on Amazon Chime mobile SDK. We will treat this as a feature request and will keep you posted.

**Comment by georgezy-amzn** [comment] 2022-05-31 18:23
Duplicate of https://github.com/aws/amazon-chime-sdk-android/issues/438

**Closed by georgezy-amzn** 2022-05-31 18:23 UTC
Labels: feature-request
