### ISSUE TITLE
iOS-React-Native-Bridge for Broadcast-ScreenShare

### ISSUE THREAD

**Issue by saurabhghadi0401** [aws/amazon-chime-sdk-ios#410] opened 2022-03-01 06:22 UTC
Hello,

I am trying to create a bridge for entire screen share on Chime-React-Native-Demo, and have setup broadcast extension as per the guide (https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/content_share.md#device-level-screen-sharing). I have created a custom-bridge to render **RPSystemBroadcastPickerView** in our code. But when I click it, it doesn't show me the app to broadcast it(extension is not getting installed on device). 
![image](https://user-images.githubusercontent.com/62549260/156115200-4bb54b47-6b67-4dc0-8deb-d9c409a4efa5.png)
![image](https://user-images.githubusercontent.com/62549260/156116012-6f891410-51bb-45ac-9d1c-fae9685619bb.png)

![image](https://user-images.githubusercontent.com/62549260/156115960-2ba2cb29-566c-43a5-8251-adcfcc6848b5.png)

I tried to run chime native iOS code and it installed the extension, but when I tried to do the same on react-native side, it's not getting installed. is there any method I need to setup so that extension will get installed When I join the meeting? 
Kindly please suggest any way to install/invoke the extension.

Thanks,
Saurabh

**Comment by hokyungh** [comment] 2022-03-01 22:10
Closing as duplicate of https://github.com/aws-samples/amazon-chime-react-native-demo/issues/130

**Closed by hokyungh** 2022-03-01 22:10 UTC
