### ISSUE TITLE
Remote video not showing up after upgrading to SDK v0.12.1

### ISSUE THREAD

**Issue by speedmetal** [aws/amazon-chime-sdk-ios#178] opened 2020-11-25 17:52 UTC
**Describe the bug**
The app we are developing correctly manage meeting video with SDK 0.11.0.
Today i've upgraded SDK to latest 0.12.1

On iOS 14.2 (iPad) the chime meeting starts, but when remote participant turn on video, no stream video is showed on local device.
Same application on android works fine.

**To Reproduce**

**Expected behavior**
If remote participants turn on camera, i wan't see his video on iOS device

**Logs**
I think the relevant error is: [ERROR] NativeMobileSDKBridge - [001:595] [101123] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.
and after
[ERROR] NativeMobileSDKBridge - Torch is not available on current camera.

Here the logs i captured
[chime.ios.sdk.log](https://github.com/aws/amazon-chime-sdk-ios/files/5598428/chime.ios.sdk.log)

**Test environment Info (please complete the following information):**
 - Device: iPad
 - OS: iOS 14.2
 - Version AmazonChimeSDK: 0.12.1
 - Version AmazonChimeSDKMedia: 0.8.1

**Additional context**
The same react native app on Android works fine.

**Comment by tianyux-amz** [comment] 2020-11-25 19:35
Hi @speedmetal,

The TURN error and Torch unavailable error should be irrelevant to your issue.

I checked the attached logs and sees like the remote video was only available for 2 seconds:
1. At 2020-11-25 18:26:18.157758+0100, the remote video track was added.
2. At 2020-11-25 18:26:18.766691+0100, a VideoRenderView was bound to tileId 2.
3. At 2020-11-25 18:26:21.057403+0100, there was no available video in the index frame anymore.
4. At 2020-11-25 18:26:21.093538+0100, the VideoRenderView was unbound from tileId 2.

Can you double check and see if you can constantly reproduce the issue if the remote video is always on during your test?

**Comment by speedmetal** [comment] 2020-11-25 19:56
This issue appears every time on iOS, with the 0.12.1 SDK i've never seen the remote video appears, i receive only the audio stream.
All the test i've done had two device: an android device (Xiaomi redmi 9) and an iOS device (iPad)
The meet starts with camera off on the two devices and audio on and all works.
If I turn on camera on iPad i see my local video and on the Android device i see the iPad stream video.
If i turn on camera on Android i see local video but on iPad the video tile remain black.

Switching camera on/off on the devices don't resolve the problem

**Comment by tianyux-amz** [comment] 2020-11-25 20:19
Could you do some tests with 1) two Android devices; and 2) Android device and Web client? I'd like to see if it's an issue from the sender side (the Android device) or the receiver side (the iOS device).

**Comment by speedmetal** [comment] 2020-11-26 09:24
@tianyux-amz in attach you can find logs between two Android devices.

All works, i don't have a web client to test the meeting.

[chime.sdk.log](https://github.com/aws/amazon-chime-sdk-ios/files/5601780/chime.sdk.log)

**Comment by speedmetal** [comment] 2020-11-30 16:48
Nobody cares?

**Comment by tianyux-amz** [comment] 2020-12-01 21:43
Hi @speedmetal,

If you [followed our README and deployed a serverless demo](https://github.com/aws/amazon-chime-sdk-ios#3-deploy-serverless-demo), you will find that the serverless demo URL can be also accessed through web and serve as a web client. That being said, since you see no issue with 2 Android devices, it's probably an issue on the iOS receiver side.

Out of curiosity, are you able to reproduce the issue with SDK v0.12.0 and Media v0.8.0?

**Comment by speedmetal** [comment] 2020-12-02 09:38
> Hi @speedmetal,
> 
> If you [followed our README and deployed a serverless demo](https://github.com/aws/amazon-chime-sdk-ios#3-deploy-serverless-demo), you will find that the serverless demo URL can be also accessed through web and serve as a web client. That being said, since you see no issue with 2 Android devices, it's probably an issue on the iOS receiver side.
> 

If all works fine on iOS with SDK 0.11.1 and the same code don't work with SDK 0.12.1 i think the problem is not on my code, i think something is wrong in 0.12.1 version

> Out of curiosity, are you able to reproduce the issue with SDK v0.12.0 and Media v0.8.0?

I'll test my app with SDK 0.12.0

**Comment by speedmetal** [comment] 2020-12-14 11:22
I've upgraded to 0.12.2 and media to 0.8.2 but nothing change.
With the same react native app I start the meeting on android device (chime sdk 0.8.2 and media sdk 0.8.2) all works fine but on iOS device (iPad) i don't see the remote video.

In attach the log captured on iOS device.
[chime.0.12.2.log](https://github.com/aws/amazon-chime-sdk-ios/files/5688439/chime.0.12.2.log)

**Comment by nealmanaktola** [comment] 2020-12-15 20:47
I am seeing this as well. 
iOS 14.3
Works fine on v0.11.x

**Comment by hokyungh** [comment] 2020-12-15 23:00
Hi @speedmetal and @nealmanaktola, there was a breaking change on [v0.12.0](https://github.com/aws/amazon-chime-sdk-ios/blob/master/CHANGELOG.md#0120---2020-11-17) which makes `renderFrameWithFrame` to `onVideoFrameReceivedWithFrame` and it now takes VideoFrame instead of `CVPixelBuffer.` For temporary workaround with our demo app, you can change `RNVideoView.m` file to

```
- (void)onVideoFrameReceivedWithFrame:(VideoFrame * _Nonnull)frame {
  if (frame == nil)
  {
    return;
  }
  VideoFramePixelBuffer* buffer = (VideoFramePixelBuffer*) frame.buffer;
  if (buffer == nil || buffer.pixelBuffer == nil)
  {
    return;
  }
  struct CGImage *imageBuffer = nil;
  VTCreateCGImageFromCVPixelBuffer(buffer.pixelBuffer, nil, &imageBuffer);
  self.image = [[UIImage alloc] initWithCGImage: imageBuffer];
  CGImageRelease(imageBuffer);
}
``` 
We'll update our demo app to use `DefaultRenderView` instead of having our own implementation.

**Comment by hokyungh** [comment] 2020-12-15 23:15
@speedmetal could you check if this [PR](https://github.com/aws-samples/amazon-chime-react-native-demo/pull/40) fixes your issue?

**Comment by nealmanaktola** [comment] 2020-12-16 03:21
@hokyungh can confirm it's working now 👍

**Comment by speedmetal** [comment] 2020-12-16 08:28
> @speedmetal could you check if this [PR](https://github.com/aws-samples/amazon-chime-react-native-demo/pull/40) fixes your issue?

@hokyungh con confirm using the [PR](https://github.com/aws-samples/amazon-chime-react-native-demo/pull/40), my app is working now! Thank you

**Comment by hokyungh** [comment] 2020-12-16 18:52
@speedmetal @nealmanaktola Thanks for confirming. Will close this issue

**Closed by hokyungh** 2020-12-16 18:52 UTC
