### ISSUE TITLE
Second time join the meeting in demo application then I can't see the video

### ISSUE THREAD

**Issue by nileshordex** [aws/amazon-chime-sdk-ios#38] opened 2020-05-15 09:10 UTC
• **Describe the bug**
I am using your demo tutorial and set up everything from the backend. Like create a meeting and create an attendee.

And then I have joined the meeting and start the video camera and working fine but if I can join the meeting again then I can't see the user live video see the only previous video thumbnail.

**• Steps to reproduce the behavior:**
1. Go to Application
2. Enter meeting ID and user name
3. Click on Join button(If the video calling is starting then after 1 min, Discount the call)
4. Again follow 2nd step
5. click on Join button
6. issue: You can't see the user live video. you can see the only thumbnail image.

**• Expected behavior**
If use joins the second time then live video show.
 
**• Test environment Info (please complete the following information):**
 - Device: iPhone6s
 - OS: 13.4.1
 - Version AmazonChimeSDK: 0.6.0
 - Version AmazonChimeSDKMedia: 0.6.0

I follow the objective-c demo.

Thank you.

**Comment by hokyungh** [comment] 2020-05-19 23:19
Thanks for reporting issue. I wasn't able to reproduce the same issue with iPhone 6S plus (12.4), so we'll try to reproduce with iPhone 6S. 

Just to confirm, did you set [setAlpha](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoObjC/ViewControllerObjC.m#L206)?

**Comment by nileshordex** [comment] 2020-05-20 11:46
Yes, I am using latest SDK 0.6.0 and already added [setAlpha](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoObjC/ViewControllerObjC.m#L206)?

**Comment by tianyux-amz** [comment] 2020-05-20 17:40
@nileshordex I was able to reproduce the issue on iPhone 6S. Will investigate and get back to you if we have more findings.

**Comment by nileshordex** [comment] 2020-05-20 17:52
Thank you so much for supporting me.

**Comment by tianyux-amz** [comment] 2020-05-21 02:42
It was caused by an unnecessary condition check in Media. Will release a fix by this Friday.

**Comment by nileshordex** [comment] 2020-05-21 06:18
Okie,
Thank you so much:)

**Comment by tianyux-amz** [comment] 2020-05-22 19:48
Hi @nileshordex, we released AmazonChimeSDK v0.6.1 and AmazonChimeSDKMedia v0.4.3 today. Please download the latest binaries and let us know if they fix your issue. Thanks!

**Comment by tianyux-amz** [comment] 2020-05-22 23:06
Note that we refreshed the AmazonChimeSDKMedia v0.4.3 just now. If you have already downloaded AmazonChimeSDKMedia v0.4.3 binary, please redownload it. Thanks!

**Comment by tianyux-amz** [comment] 2020-05-27 20:18
Closing the issue as we don't hear back from the issue reporter. Feel free to reopen if the issue still exists with AmazonChimeSDKMedia v0.4.3.

**Closed by tianyux-amz** 2020-05-27 20:18 UTC
