### ISSUE TITLE
Network condition hooks aren't firing

### ISSUE THREAD

**Issue by schonfeld** [aws/amazon-chime-sdk-ios#164] opened 2020-11-10 21:49 UTC
**Describe the bug**

I cannot seem to get `connectionDidBecomePoor` to fire, or even `videoTileDidPause` w/ `.pausedForPoorConnection`. I'm running the demo app on 2 physical iPhone devices, running in debug mode with breakpoints set for each health observer. While in-call, I turn on the network link conditioner to both 3G and "Very Bad Network". The call quality significantly drops almost immediately, but none of the health callbacks seem to get triggered at all. 

Am I missing some crucial step here?

**To Reproduce**
1. Fire up the app using 2 physical devices while in xcode debug mode, breakpoints set on `connectionDidBecomePoor`.
2. While in an active meeting, engage the network link conditioner at 3G mode

**Expected behavior**
The `connectionDidBecomePoor` event should fire when the network link conditioner is turned on a limiting setting.

**Test environment Info (please complete the following information):**
 - Device: iPhone 11 x2
 - OS: iOS 14.1
 - Version AmazonChimeSDK: 0.11.1
 - Version AmazonChimeSDKMedia: 0.7.1

**Comment by hokyungh** [comment] 2020-11-11 01:10
Hi @schonfeld, thank you for reporting. Do you mind creating new bad network in link conditioner
with
```
In Bandwith 1000
In Packet Loss 50
In Delay 500
Out Bandwidth 1000
Out Packet Loss 50
Out Delay 500
DNS Delay 0
```
and see if connectionDidBecomePoor fires?

`connectionDidBecomePoor` is based on the jitter/loss/RTT of audio, so it could be that it didn't think of it as very bad network. It could be lower loss with just low bandwidth.

You can also use `signalStrengthDidChange` to see what was the signal for that attendee.

For videoTileDidPause, could you add few more attendees and start sharing videos among them? It might not be as severely constrained to pause the video so adding more should restrain the network more.

**Comment by schonfeld** [comment] 2020-11-11 16:16
> Hi @schonfeld, thank you for reporting. Do you mind creating new bad network in link conditioner
> with
> 
> ```
> In Bandwith 1000
> In Packet Loss 50
> In Delay 500
> Out Bandwidth 1000
> Out Packet Loss 50
> Out Delay 500
> DNS Delay 0
> ```
> 
> and see if connectionDidBecomePoor fires?
> 
> `connectionDidBecomePoor` is based on the jitter/loss/RTT of audio, so it could be that it didn't think of it as very bad network. It could be lower loss with just low bandwidth.
> 
> You can also use `signalStrengthDidChange` to see what was the signal for that attendee.
> 
> For videoTileDidPause, could you add few more attendees and start sharing videos among them? It might not be as severely constrained to pause the video so adding more should restrain the network more.

Thanks for that -- I'm able to consistently produce both `connectionDidBecomePoor` and `connectionDidRecover` using the above conditioner settings.

Say I wanted to prompt a user w/ bad connection to switch to audio-only mode, would the "best" way to detect a bad network be a combination of the user's own signal strength, in combination with the `connectionDidBecomePoor` event?

**Comment by alnlau** [comment] 2020-12-29 19:33
Hello @schonfeld,

We recommend using `connectionDidBecomePoor` to prompt a user with bad connection to switch to audio only.

`connectionDidBecomePoor` signifies that more than 50% network packet loss rate over a 5 second window has been observed for 3 consecutive intervals.
`signalStrengthDidChange` signifies the amount of audio data lost by an attendee in the last second and updates in real time.

**Comment by dylonChime** [comment] 2021-03-05 19:58
I'll close this for now. Feel free to reopen if you feel the issue is not resolved, you have further questions, or you have a feature request that might improve the experience.

**Closed by dylonChime** 2021-03-05 19:58 UTC
Labels: question
