### ISSUE TITLE
Unable to rotate my application when i'm sharing my application screen(InAppScreenShare).

### ISSUE THREAD

**Issue by kalebupatan7** [aws/amazon-chime-sdk-ios#274] opened 2021-04-09 07:08 UTC
Hi, I'm facing an issue when share my app screen(Not device level share), it's not rotating. If I start screen share portrait mode, in between screen share I'm unable to rotate to landscape & vice versa.

Steps to Reproduce:
1. Start Amazon chime meeting session
2. Then start screen share
3. if we rotated screen, we can't get rotation
4. After stopping screen share, we can able to rotate.

Please help me to resolve this issue as soon as possible

**Comment by dylonChime** [comment] 2021-04-12 08:47
I am able to reproduce this issue.

While we investigate, do you mind providing the following info?:

- Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Comment by dylonChime** [comment] 2021-04-13 07:10
Hi @kalebupatan7, this is a [limitation of RPScreenRecorder](https://github.com/aws/amazon-chime-sdk-ios/blob/71dd4a92cabe73b2e98ffa0556d0320c0763eef9/AmazonChimeSDK/AmazonChimeSDK/audiovideo/contentshare/InAppScreenCaptureSource.swift#L15), which we are using in our demo to implement the VideoCaptureSource used by screen share. If you need to support rotation, we recommend you use [device level sharing with a broadcast extension](https://aws.amazon.com/blogs/business-productivity/how-to-screen-share-from-ios-devices-using-amazon-chime-sdk/) or implement a custom [InAppScreenCaptureSource](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/contentshare/InAppScreenCaptureSource.swift#L17).

I'll leave this open as a feature request to provide another InAppScreenCaptureSource implementation that allows for rotation during screen share.

**Comment by alnlau** [comment] 2021-07-15 20:49
Closing this issue since this is a limitation of `RPScreenRecorder` and we are currently not planning on working on another implementation of `InAppScreenCaptureSource` that allows for rotation during screen share. See Dylon's suggestion for a workaround.

**Closed by alnlau** 2021-07-15 20:49 UTC
Labels: enhancement
