### ISSUE TITLE
Third attendee video tile appears with delay and Sometimes doesn't come

### ISSUE THREAD

**Issue by manindra86** [aws/amazon-chime-sdk-ios#49] opened 2020-06-01 18:41 UTC
**Describe the bug**
Starting a meeting with chime mobile SDK and make attendees join the meeting and let them share their video on the call. For two user video streaming works fine but once the third attendee shares the video then the third video tile in the ios app appears after some delay. 

**To Reproduce**
1. Start the meeting and share the video
2. Join the meeting from the web client and start the video
3. Again, join the meeting from some other web client and start the video

**Expected behavior**
Once the third person joins the meeting and shares the video then third-person video tile should appear without too much delay in the iOS app.

**Logs**
Following logs comes continously:
2020-06-01 23:37:07.483545+0530 DemoApp[2773:700249] [ERROR]  MeetingViewController - [428:881] [25167] (RTCVideoEncoderH264.mm:845): Encode callback failed

**Test environment Info (please complete the following information):**
 - Device:  iPhone XR
 - OS:  iOS 13.3
 - Version AmazonChimeSDK: 0.6.1
 - Version AmazonChimeSDKMedia: 0.4.3

**Comment by wanghaor-amzn** [comment] 2020-06-02 18:15
@manindra86 It seems this log is irrelevant to this issue since this issue you report is about receiving a third video stream. Can you provide more logs near the timestamp of receiving the third video stream please? Thanks.

**Comment by manindra86** [comment] 2020-06-09 16:52
Hi @wanghaor-amzn ,
These are the logs coming on console once third attendee tile is not coming

2020-06-09 22:19:29.565610+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [572:802] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
[573:813] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:30.576466+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [573:813] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:30.580623+0530 MOBIINSPECT[26708:537012] [INFO] MeetingViewController - Media metrics have been received: [videoReceivePacketLossPercent: 0, videoReceiveBitrate: 61685.83133770063, videoAvailableReceiveBandwidth: 163262, audioSendPacketLossPercent: 0, audioReceivePacketLossPercent: 0]
[574:821] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:31.584267+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [574:821] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:31.586695+0530 MOBIINSPECT[26708:537012] [INFO] MeetingViewController - Media metrics have been received: [audioSendPacketLossPercent: 0, videoAvailableReceiveBandwidth: 163262, videoReceiveBitrate: 54895.57111449215, videoReceivePacketLossPercent: 0, audioReceivePacketLossPercent: 0]
[575:827] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:32.590931+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [575:827] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:32.591885+0530 MOBIINSPECT[26708:537012] [INFO] MeetingViewController - Media metrics have been received: [audioSendPacketLossPercent: 0, videoAvailableReceiveBandwidth: 163262, videoReceiveBitrate: 53146.56504274384, videoReceivePacketLossPercent: 0, audioReceivePacketLossPercent: 0]
[576:830] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:33.593577+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [576:830] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:33.594452+0530 MOBIINSPECT[26708:537012] [INFO] MeetingViewController - Media metrics have been received: [videoReceiveBitrate: 58808.84927836574, videoAvailableReceiveBandwidth: 163262, audioSendPacketLossPercent: 0, videoReceivePacketLossPercent: 0, audioReceivePacketLossPercent: 0]
[577:836] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:34.599380+0530 MOBIINSPECT[26708:541317] [ERROR] Partho Meeting - [577:836] [58887] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-09 22:19:34.601226+0530 MOBIINSPECT[26708:537012] [INFO] MeetingViewController - Media metrics have been received: [audioSendPacketLossPercent: 0, videoAvailableReceiveBandwidth: 163262, videoReceivePacketLossPercent: 0, videoReceiveBitrate: 64556.34909824142, audioReceivePacketLossPercent: 0]

**Comment by manindra86** [comment] 2020-06-11 11:19
Some more logs:
2020-06-11 16:34:55.895500+0530 DemoApp[511:59811] [ERROR]  MeetingController - [739:064] [171807] (RTCVideoEncoderH264.mm:845): Encode callback failed
2020-06-11 16:34:56.426922+0530 DemoApp[511:54518] [INFO] MeetingViewController - Signal strength changed for PRAKASH SEJWANI: high
[739:760] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:56.591706+0530 DemoApp[511:57848] [ERROR] MeetingController - [739:760] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:56.594368+0530 DemoApp[511:54518] [INFO] MeetingViewController - Media metrics have been received: [audioReceivePacketLossPercent: 66, videoSendFps: 9.930447148174188, videoAvailableSendBandwidth: 68000, videoAvailableReceiveBandwidth: 75705, videoReceivePacketLossPercent: 0, videoSendBitrate: 13966.18086919218, audioSendPacketLossPercent: 100, videoSendPacketLossPercent: 0, videoSendRttMs: 423, videoReceiveBitrate: 71213.22258898674]
[740:766] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:57.597797+0530 DemoApp[511:57848] [ERROR] MeetingController - [740:766] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:57.601297+0530 DemoApp[511:54518] [INFO] MeetingViewController - Media metrics have been received: [videoAvailableReceiveBandwidth: 76508, videoSendRttMs: 296, audioReceivePacketLossPercent: 0, videoSendBitrate: 34063.46836175436, videoReceivePacketLossPercent: 0, videoSendFps: 7.456105904539974, videoSendPacketLossPercent: 0.02907062672734614, videoAvailableSendBandwidth: 68000, videoReceiveBitrate: 30031.20628857913, audioSendPacketLossPercent: 4]
[741:770] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:58.601407+0530 DemoApp[511:57848] [ERROR] MeetingController - [741:770] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:58.604265+0530 DemoApp[511:54518] [INFO] MeetingViewController - Media metrics have been received: [videoSendRttMs: 342, videoAvailableReceiveBandwidth: 76508, audioSendPacketLossPercent: 0, videoReceivePacketLossPercent: 0, videoReceiveBitrate: 29975.95346552118, videoSendPacketLossPercent: 0, videoSendBitrate: 45115.40443121923, audioReceivePacketLossPercent: 0, videoAvailableSendBandwidth: 68000, videoSendFps: 7.474057546256942]
[742:776] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:59.607431+0530 DemoApp[511:57848] [ERROR] MeetingController - [742:776] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:34:59.609659+0530 DemoApp[511:54518] [INFO] MeetingViewController - Media metrics have been received: [videoReceivePacketLossPercent: 0, audioSendPacketLossPercent: 0, videoSendPacketLossPercent: 0, videoAvailableSendBandwidth: 68000, videoAvailableReceiveBandwidth: 76508, videoReceiveBitrate: 27391.54035659109, videoSendFps: 7.456320872329892, audioReceivePacketLossPercent: 0, videoSendRttMs: 342, videoSendBitrate: 40172.66850788084]
[743:778] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:35:00.609632+0530 DemoApp[511:57848] [ERROR] MeetingController - [743:778] [54299] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps
2020-06-11 16:35:00.612640+0530 DemoApp[511:54518] [INFO] MeetingViewController - Media metrics have been received: [videoSendPacketLossPercent: 0, videoSendFps: 7.47979706811901, videoReceiveBitrate: 25084.24744764391, videoSendBitrate: 45078.2436638639, audioSendPacketLossPercent: 0, videoReceivePacketLossPercent: 0, audioReceivePacketLossPercent: 0, videoAvailableReceiveBandwidth: 76508, videoSendRttMs: 314, videoAvailableSendBandwidth: 68000]

**Comment by wanghaor-amzn** [comment] 2020-07-14 01:20
Hi, @manindra86 would you please try the latest AmazonChimeSDK v0.7.1 and AmazonChimeSDKMedia v0.5.1 to see if this issue is still reproducible?

**Comment by wanghaor-amzn** [comment] 2020-07-20 21:26
Hi, @manindra86 we just released AmazonChimeSDK v0.8.0 and AmazonChimeSDKMedia v0.5.2. Please let us know if you could still experience such an issue

**Comment by tianyux-amz** [comment] 2020-07-30 00:39
Closing the issue as we did not hear back from the builder. Please reopen the issue if you have more questions.

**Closed by tianyux-amz** 2020-07-30 00:39 UTC

**Comment by amrit42087** [comment] 2020-10-21 13:18
Hi @wanghaor-amzn , I am using AmazonChimeSDK v0.11.0 and AmazonChimeSDKMedia v0.7.0. I am still facing this issue. Sometime the video tile does not appear and sometimes it's too late.
