### ISSUE TITLE
Device level screen share not sharing audio feed

### ISSUE THREAD

**Issue by cHaLkdusT** [aws/amazon-chime-sdk-ios#503] opened 2022-07-26 10:40 UTC
**Describe the bug**
Implemented device level screen sharing, however, audio not shared from other apps (eg playing video YouTube) 

**To Reproduce**
1. Implement [device level screen sharing](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/content_share.md#device-level-screen-sharing)

**Expected behavior**
Audio should be shared when sharing device level screen sharing

**Logs**
N/A

**Screenshots**
N/A

**Test environment Info (please complete the following information):**
 - Device: Any device
 - OS: iOS 13
 - Version AmazonChimeSDK-Bitcode: 0.21.0
 - Version AmazonChimeSDKMedia-Bitcode: 0.17.0
 - Can you reproduce this in the demo app? Yes

**Additional context**
N/A

**Comment by ziyiz-amzn** [comment] 2022-07-28 18:31
Thank you for reporting. This seems a duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/300

**Comment by cHaLkdusT** [comment] 2022-07-29 00:04
Hi @ziyiz-amzn, it is indeed a duplicate issue of https://github.com/aws/amazon-chime-sdk-ios/issues/300

**Comment by georgezy-amzn** [comment] 2022-08-04 00:16
Close as duplicate of #300

**Closed by georgezy-amzn** 2022-08-04 00:16 UTC
Labels: duplicate
