### ISSUE TITLE
Add support to bind video tiles to more than one view.

### ISSUE THREAD

**Issue by jpmunoz9** [aws/amazon-chime-sdk-ios#224] opened 2021-01-28 17:28 UTC
Currently a given video tile can only be bind to one view, it would be ideal if it could be bind to multiple views, this would open up our ability to build more powerful UIs. For example it would be great to have a floating active speaker that shows whoever is talking above whatever UI is underneath showing all other participants.

**Comment by piv199** [comment] 2021-01-29 15:15
This could be achieved with VideoFrameBroadcaster from https://github.com/aws/amazon-chime-sdk-android/issues/204

This duplicates https://github.com/aws/amazon-chime-sdk-ios/issues/211

**Comment by dylonChime** [comment] 2021-01-29 17:38
Closing this as a duplicate of #211.

**Closed by dylonChime** 2021-01-29 17:38 UTC
Labels: duplicate
