### ISSUE TITLE
Mobile video Black Tile issue

### ISSUE THREAD

**Issue by jumcclure** [aws/amazon-chime-sdk-ios#599] opened 2023-05-18 17:03 UTC
**Describe the bug**
We are experiencing a problem where a black video tile appears in video meetings under the following circumstances:

1. when multiple participants join the meeting with their video turned on.
2. when someone leaves the meeting.
3. pin the video of the person you want.
4. choose to hide self-video view.

**To Reproduce**
1. The screen re-rendered multiple times
2. SDK re-initialized all the videos and re-rendered them again.
3. Occasionally, black tiles appeared, app eventually crashed with the error message "unable to find node bind video."
4. If other participants left, black tiles appeared

**Expected behavior**
Video tiles continue to display normally.

**Logs**
[chime_video_black_tile_logs_with_screenshots.zip](https://github.com/aws/amazon-chime-sdk-android/files/11509707/chime_video_black_tile_logs_with_screenshots.zip)
See attached file.

**Screenshots**
See attached file.

**Test environment Info (please complete the following information):**
 - Device: iPhone13, iPhone14
 - OS: iOS 15.7.5, iOS 16.4.1
 - Version AmazonChimeSDK: v0.22.7
 - Version AmazonChimeSDKMedia: v0.22.7
 - Can you reproduce this in the demo app? Yes
 
**Additional context**
Originally submitted here - https://github.com/aws/amazon-chime-sdk-js/issues/2662

**Comment by georgezy-amzn** [comment] 2023-05-18 19:54
This is duplicate of https://github.com/aws/amazon-chime-sdk-android/issues/563

**Closed by georgezy-amzn** 2023-05-18 19:54 UTC
