### ISSUE TITLE
Meeting readiness checker for IOS & Android native SDKs

### ISSUE THREAD

**Issue by BonVit** [aws/amazon-chime-sdk-ios#593] opened 2023-05-05 09:31 UTC
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-ios/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for troubleshooting.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
We want to have a way to perform a "tech check" before meeting starts to ensure the user have a good video call experience.
There is already a solution for js sdk - meeting readiness checker:
https://github.com/aws/amazon-chime-sdk-js#meeting-readiness-checker
We want to know if there is a way to do it with android/ios sdk.

## Tell us about the problem you are trying to solve and why is it hard?
We are looking for a way to inform user about any potential issues he can encounter in a video call - whether its network, hardware (e.g. camera not functioning) or software (e.g. codec issues) issues.

## How are you currently solving a problem?
No solution currently.

## Additional context
JS chime sdk already has a solution for this:
https://github.com/aws/amazon-chime-sdk-js#meeting-readiness-checker
I also created the same request for chime Android SDK

**Comment by yochum** [comment] 2024-11-05 19:14
Closing as duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/464

**Closed by yochum** 2024-11-05 19:14 UTC
Labels: feature-request
