### ISSUE TITLE
Extract audio from Chime (CMSampleBuffer)

### ISSUE THREAD

**Issue by andresuhartanto** [aws/amazon-chime-sdk-ios#509] opened 2022-08-05 11:17 UTC
Hi all,

We have a question about Chime, here's the situation:
Our team is building a video broadcast feature using IVS, in this broadcast feature we also can call the viewers, in this case we are using Chime to make the video call. now we can get the video from Chime from this function _onVideoFrameReceived_ in class VideoRenderView, but we also need to extract the Audio from the chime call. so is there anyway for us to extract the audio from Chime just like on video?

Thank you!

**Comment by georgezy-amzn** [comment] 2022-08-08 18:18
Hi @andresuhartanto,

For now, the SDK doesn't support, but our team is currently undertaking a significant project to align our end to end audio processing pipeline with WebRTC protocols, once it's done, you will be able to extract audio. For more details, please refer to #300.

Closing as duplicate of #300.

**Closed by georgezy-amzn** 2022-08-08 18:18 UTC
Labels: feature-request
