### ISSUE TITLE
M1 Mac - Unable to compile the app using Amazon Chime SDK for simulator

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios#392] opened 2022-01-17 05:27 UTC
Our app is using Amazon Chime SDK which is not compilable on Apple M1 Mac when compiling it for simulator. We don't see any support for arm64 in Amazon sdk. Is there any plan when a new SDK version might be available for being able to compile on a M1 Mac?

**Comment by hokyungh** [comment] 2022-01-19 00:09
Hi @arehman86 as a workaround you can use Rosetta to open Xcode. Closing it duplicate of #295

**Closed by hokyungh** 2022-01-19 00:09 UTC
