### ISSUE TITLE
Custom Audio Input and Output

### ISSUE THREAD

**Issue by gaborszanto** [aws/amazon-chime-sdk-ios#553] opened 2022-12-16 15:22 UTC
Can we expect custom audio input and output API similar to VideoSource? If yes, is there any ETA for that?

This is already possible on the web with some Web Audio plumbing.

**Comment by alnlau** [comment] 2022-12-21 18:35
This is an existing feature request. However, there is currently no ETA (see https://github.com/aws/amazon-chime-sdk-ios/issues/294#issuecomment-1047251733 for details).

Closing as duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/294

**Closed by alnlau** 2022-12-21 18:35 UTC
Labels: duplicate
